# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=200)),
                ('team_slug', models.CharField(max_length=200)),
                ('ppg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('apg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('rpg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('bpg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('spg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fga', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fgm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('tpg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('threept_attempted', models.DecimalField(decimal_places=1, max_digits=5)),
                ('threept_made', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fastbreak_points', models.DecimalField(decimal_places=1, max_digits=5)),
                ('paint_points', models.DecimalField(decimal_places=1, max_digits=5)),
                ('turnover_points', models.DecimalField(decimal_places=1, max_digits=5)),
                ('secondchance_points', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
