# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20170418_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='Team', max_length=200),
            preserve_default=False,
        ),
    ]
