# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Season_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('apg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('rpg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('per', models.DecimalField(decimal_places=2, max_digits=5)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
    ]
