# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_log_id', models.CharField(max_length=200)),
                ('player_id', models.CharField(max_length=200)),
                ('team_id', models.CharField(max_length=200)),
                ('opponent_id', models.CharField(max_length=200)),
                ('home_team_score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('away_team_score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('team_score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('team_outcome', models.CharField(max_length=200)),
                ('ppg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('apg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('rpg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('bpg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('spg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fga', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fgm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('tpg', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=200)),
                ('player_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=10)),
                ('team_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Season_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('apg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('rpg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('bpg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('spg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fga', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fgm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('tpg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('threept_attempted', models.DecimalField(decimal_places=1, max_digits=5)),
                ('threept_made', models.DecimalField(decimal_places=1, max_digits=5)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
    ]
